CREATE TABLE EMPLOYEE 
(ENAME VARCHAR(20) NOT NULL, 
ESRNO VARCHAR(7) PRIMARY KEY CHECK(LENGTH(ESRNO)=6), 
BDATE DATE, 
ADDRESS VARCHAR(20), 
SEX CHAR(3) DEFAULT('M'), 
SALARY NUMBER(7) CHECK(SALARY BETWEEN 20000 AND 40000), 
MGRSRNO VARCHAR(6), 
DNO NUMBER(3));

INSERT INTO EMPLOYEE VALUES 
('AJIT NAYAK',133100,(TO_DATE('1955-04-25','YYYY-MM-DD')),'73 BOSTON', 'M',35000,'',1);

INSERT INTO EMPLOYEE VALUES 
('SATYA',495823,(TO_DATE('1966-07-17','YYYY-MM-DD')),'26 FINE OAK', 'M',32770,133100,4);

INSERT INTO EMPLOYEE VALUES 
('AJIT BEHERA',315152,(TO_DATE('1971-07-09','YYYY-MM-DD')),'10 KALINGA', 'M',32802,133100,3);

INSERT INTO EMPLOYEE VALUES 
('UMASHANKAR',216852,(TO_DATE('1967-07-17','YYYY-MM-DD')),'26 FINE OAK', 'M',32770,133100,2);

INSERT INTO EMPLOYEE VALUES 
('BHAGWAT',215152,(TO_DATE('1971-03-23','YYYY-MM-DD')),'55 FLORIDA', 'M',32802,216852,2);

INSERT INTO EMPLOYEE VALUES 
('MEENAKSHI',334548,(TO_DATE('1979-04-25','YYYY-MM-DD')),'73 BRIKLY', 'F',25125,315152,3);

INSERT INTO EMPLOYEE VALUES 
('JASWASI', 215485,(TO_DATE('1979-08-12','YYYY-MM-DD')), '17 BOSTON', 'M', 20500, 495823, 4);

INSERT INTO EMPLOYEE VALUES 
('NIHAR NAYAK', 334524 ,(TO_DATE('1966-12-17','YYYY-MM-DD')), '73 DALLAS', 'M', 29105, 315152, 3);

INSERT INTO EMPLOYEE VALUES 
('DEBASMITA', 295485,(TO_DATE('1970-04-16','YYYY-MM-DD')), '1 QUEENS LAND', 'F', 20500, 216852, 2);

CREATE TABLE DEPARTMENT 
(DNAME VARCHAR(12) CHECK(DNAME IN ('RESEARCH', 'ADMIN', 'PROJECT', 'ACADEMIC')), 
DNUMBER NUMBER(2) PRIMARY KEY CHECK(DNUMBER BETWEEN 1 AND 4), 
MGRSRNO VARCHAR(6), 
MGRSTARTD DATE);

INSERT INTO DEPARTMENT VALUES 
('RESEARCH', 4, 495823, TO_DATE('1999-04-20','YYYY-MM-DD'));

INSERT INTO DEPARTMENT VALUES 
('ADMIN', 1, 133100, TO_DATE('1988-01-06','YYYY-MM-DD'));

INSERT INTO DEPARTMENT VALUES 
('PROJECT', 2, 216852, TO_DATE('1999-07-17','YYYY-MM-DD'));

INSERT INTO DEPARTMENT VALUES 
('ACADEMIC', 3, 315152, TO_DATE('1989-12-20','YYYY-MM-DD'));

CREATE TABLE DEPT_LOCATIONS 
(DNUMBER NUMBER(2) CHECK(DNUMBER BETWEEN 1 AND 4), 
DLOCATION VARCHAR(12) CHECK(DLOCATION IN ('SINGAPORE', 'INDIA', 'QUUENSLAND', 'LONDON')));

INSERT INTO DEPT_LOCATIONS VALUES (2, 'SINGAPORE');

INSERT INTO DEPT_LOCATIONS VALUES (1, 'INDIA' );

INSERT INTO DEPT_LOCATIONS VALUES (4, 'QUUENSLAND' );

INSERT INTO DEPT_LOCATIONS VALUES (3, 'LONDON');

CREATE TABLE PROJECT 
(PNAME VARCHAR(18) CHECK(PNAME IN ('NETWORKING', 'BIO INFORMATICS', 'LINUX')), 
PNUMBER NUMBER(3) PRIMARY KEY, 
PLOCATION VARCHAR(15) CHECK(PLOCATION IN ('KOREA', 'SOUTH AFRICA', 'INDIA')), 
DNUM NUMBER(2));

INSERT INTO PROJECT VALUES ('NETWORKING', 11 ,'KOREA', 4);

INSERT INTO PROJECT VALUES ('BIO INFORMATICS', 19, 'SOUTH AFRICA', 3);

INSERT INTO PROJECT VALUES ('LINUX', 17, 'INDIA', 2 );

CREATE TABLE WORKS_ON 
(ESRNO VARCHAR(6), 
PNO NUMBER(3) CHECK(PNO>0), 
HOURS DECIMAL(5,2) CHECK(HOURS>0));

INSERT INTO WORKS_ON VALUES (315152, 19, 1.25) ;

INSERT INTO WORKS_ON VALUES (334548, 19, 3.28) ;

INSERT INTO WORKS_ON VALUES (215485, 17, 1.25) ;

INSERT INTO WORKS_ON VALUES (295485, 17, 5.35) ;

INSERT INTO WORKS_ON VALUES (334548, 19, 2.54) ;

INSERT INTO WORKS_ON VALUES (295485, 17, 7.2) ;

INSERT INTO WORKS_ON VALUES (216852, 17, 2.41);

INSERT INTO WORKS_ON VALUES (334524, 19, 3.24) ;

INSERT INTO WORKS_ON VALUES (295485, 17, 1.36) ;

INSERT INTO WORKS_ON VALUES (495823, 11, 2.36) ;

INSERT INTO WORKS_ON VALUES (215152, 17, 1.25) ;

INSERT INTO WORKS_ON VALUES (495823,11, 3.14) ;

INSERT INTO WORKS_ON VALUES (315152,19, 2.05) ;

INSERT INTO WORKS_ON VALUES (334548, 19, 2.5) ;

INSERT INTO WORKS_ON VALUES (495823, 11, 5.27);

INSERT INTO WORKS_ON VALUES (215152, 17, 2.32) ;

INSERT INTO WORKS_ON VALUES (495823, 11, 4.15) ;

SELECT SALARY FROM EMPLOYEE;

SELECT ENAME,SALARY FROM EMPLOYEE;

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_MGRSRNO 
FOREIGN KEY(MGRSRNO) 
REFERENCES EMPLOYEE(ESRNO)  
ON DELETE CASCADE;

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_DNO 
FOREIGN KEY(DNO) 
REFERENCES DEPARTMENT(DNUMBER) 
ON DELETE CASCADE;

ALTER TABLE DEPARTMENT 
ADD CONSTRAINT FK_MGRSRNO_DEPT 
FOREIGN KEY(MGRSRNO) 
REFERENCES EMPLOYEE(ESRNO) 
ON DELETE CASCADE;

ALTER TABLE DEPT_LOCATIONS 
ADD CONSTRAINT FK_DNUMBER_DEPT_LOCATIONS 
FOREIGN KEY(DNUMBER) 
REFERENCES DEPARTMENT(DNUMBER) 
ON DELETE CASCADE;

ALTER TABLE WORKS_ON 
ADD CONSTRAINT FK_ESRNO_WORKS_ON 
FOREIGN KEY(ESRNO) 
REFERENCES EMPLOYEE(ESRNO) 
ON DELETE CASCADE;

ALTER TABLE WORKS_ON 
ADD CONSTRAINT FK_PNO_WORKS_ON 
FOREIGN KEY(PNO) 
REFERENCES PROJECT(PNUMBER) 
ON DELETE CASCADE;

SELECT ENAME , SALARY FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;

SELECT ENAME FROM EMPLOYEE 
WHERE SEX = 'F';

SELECT * FROM EMPLOYEE;

SELECT ENAME FROM EMPLOYEE 
WHERE SEX = 'F';

SELECT * FROM EMPLOYEE 
WHERE SALARY= 
    (SELECT MAX(SALARY)FROM EMPLOYEE);

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT * FROM DEPARTMENT;

SELECT * FROM DEPT_LOCATIONS;

SELECT * FROM PROJECT;

SELECT * FROM WORKS_ON;

SELECT * FROM EMPLOYEE;

SELECT * FROM WORKS_ON;

SELECT * FROM EMPLOYEE 
WHERE ENAME LIKE '%A%';

SELECT ENAME, SEX FROM EMPLOYEE  
WHERE SALARY=  
    (SELECT MAX(SALARY)FROM EMPLOYEE);

SELECT ENAME, SALARY FROM EMPLOYEE  
WHERE SALARY=  
    (SELECT MAX(SALARY)FROM EMPLOYEE);

select ENAME,ADDRESS,DNO,DNAME 
		FROM employee,department 
        WHERE employee.DNO = department.DNUMBER;

SELECT ENAME,ADDRESS,DNO,DNAME 
FROM EMPLOYEE, DEPARTMENT 
WHERE EMPLOYEE.DNO = DEPARTMENT.DNUMBER;

SELECT ENAME, PNAME, PLOCATION 
FROM EMPLOYEE, PROJECT 
WHERE EMPLOYEE.DNO = PROJECT.DNUM AND EMPLOYEE.ENAME = 'SATYA';

SELECT ENAME, DNO, DNAME 
FROM EMPLOYEE, DEPARTMENT 
WHERE EMPLOYEE.DNO = DEPARTMENT.DNUMBER AND DEPARTMENT.DNAME!= 'ACADEMIC';

SELECT * FROM employee,project 
WHERE employee.DNO = project.DNUM AND PLOCATION = 'SOUTH AFRICA';

SELECT * FROM PROJECT, EMPLOYEE 
WHERE project.DNUM = employee.DNO AND PLOCATION = 'SOUTH AFRICA';

SELECT * FROM PROJECT, EMPLOYEE 
WHERE project.DNUM = employee.DNO AND PLOCATION = 'SOUTH AFRICA';

SELECT * FROM EMPLOYEE, PROJECT 
WHERE project.DNUM = employee.DNO AND PLOCATION = 'SOUTH AFRICA';

